## 0.4 벡터와 행렬

행렬 곱·역행렬·전치를 다루고, 심화로 고윳값·고유벡터와 대각화를 확인한다.

### 0.4.1 벡터와 행렬 곱 (게이트가 상태에 작용하는 연산)

In [1]:
import numpy as np

A = np.array([[1,3],[2,5]]); v = np.array([[2],[7]])
print("A @ v =\n", A @ v)   # [[23],[39]]

A @ v =
 [[23]
 [39]]


### 0.4.2 항등행렬과 역행렬

In [2]:
import numpy as np

A = np.array([[2.,1.],[1.,3.]]); I = np.eye(2)
print("A^-1 =\n", np.linalg.inv(A))
assert np.allclose(A @ np.linalg.inv(A), I)
print("검증 통과: A·A⁻¹ = I")

A^-1 =
 [[ 0.6 -0.2]
 [-0.2  0.4]]
검증 통과: A·A⁻¹ = I


### 0.4.3 전치

In [3]:
import numpy as np

X = np.array([[0,2],[3,1]]); Y = np.array([[2,4],[5,3]])
assert np.array_equal((X@Y).T, Y.T@X.T)
print("검증 통과: (XY)ᵀ = YᵀXᵀ")

검증 통과: (XY)ᵀ = YᵀXᵀ


### 0.4.4 심화: 고윳값·고유벡터와 대각화
Av = λv 를 만족하는 v가 고유벡터, λ가 고윳값이다. 고유기저로 바꾸면 행렬이 대각화된다.

In [4]:
import numpy as np

A = np.array([[2., 1.],[1., 2.]])
vals, vecs = np.linalg.eig(A)
print("고윳값:", np.round(vals,4))
print("고유벡터(열):\n", np.round(vecs,4))
# Av = λv 검증
for i in range(2):
    assert np.allclose(A @ vecs[:,i], vals[i]*vecs[:,i])
print("검증 통과: A v = λ v")

고윳값: [3. 1.]
고유벡터(열):
 [[ 0.7071 -0.7071]
 [ 0.7071  0.7071]]
검증 통과: A v = λ v


In [5]:
import numpy as np

# 대각화: D = P^-1 A P (고유기저에서 대각행렬)
A = np.array([[2., 1.],[1., 2.]])
vals, P = np.linalg.eig(A)
D = np.linalg.inv(P) @ A @ P
print("D = P^-1 A P =\n", np.round(D, 6))   # 대각 = 고윳값
# 원래 행렬 복원: A = P D P^-1
assert np.allclose(P @ D @ np.linalg.inv(P), A)
print("검증 통과: 대각화와 복원")

D = P^-1 A P =
 [[3. 0.]
 [0. 1.]]
검증 통과: 대각화와 복원
